name: Sync, Filter, Convert

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo branch
        uses: actions/checkout@v4
        with:
          ref: repo

      - name: Download upstream index.json
        run: |
          curl -L \
            -o index.json \
            https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.json

      - name: Install Python
        run: sudo apt-get install -y python3

      - name: Convert to legacy format
        run: python3 scripts/convert-to-legacy.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.json index.min.json
          git commit -m "Sync + filter + convert to legacy format" || echo "No changes"

      - name: Push changes
        run: git push origin repo
