name: Update Extension List

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate extension list
        run: |
          ls repo > extension-list.txt

      - name: Commit list
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add extension-list.txt
          git commit -m "Update extension list" || echo "No changes"
          git push origin repo
